<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<NoWarn>BL9993;BL0007;BL0005</NoWarn>

		<TargetFrameworks>net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>

		<RazorLangVersion>7.0</RazorLangVersion>
		<LangVersion>latest</LangVersion>
		<OutputType>Library</OutputType>
		<IsPackable>true</IsPackable>

		<PackageId>BLECoder.Radzen.Blazor</PackageId>

		<Version>8.3.4-custom.1</Version>

		<Product>Radzen.Blazor (BLECoder Fork)</Product>
		<Copyright>Radzen Ltd. / Forked by BLECoder</Copyright>
		<Authors>BLECoder; Radzen Ltd.</Authors>

		<Description>
			An unofficial fork of the Radzen Blazor component library, maintained by BLECoder.
			Original Description: Radzen Blazor is the most sophisticated free UI component library for Blazor, featuring 100+ native components.
		</Description>

		<PackageTags>blazor material design fluent fluentui components datagrid scheduler charts fork</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<PackageProjectUrl>https://github.com/ace90210/radzen-blazor</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ace90210/radzen-blazor</RepositoryUrl>

		<PackageIcon>icon.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Title>BLECoder Fork of Radzen Components</Title>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DartSassBuilder" Version="1.1.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Condition="'$(TargetFramework)' == 'net6.0'" Version="6.0.25" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Condition="'$(TargetFramework)' == 'net6.0'" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Condition="'$(TargetFramework)' == 'net7.0'" Version="7.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Condition="'$(TargetFramework)' == 'net7.0'" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Condition="'$(TargetFramework)' == 'net8.0'" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Condition="'$(TargetFramework)' == 'net8.0'" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Condition="'$(TargetFramework)' == 'net9.0'" Version="9.*-*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Condition="'$(TargetFramework)' == 'net9.0'" Version="9.*-*" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Condition="'$(TargetFramework)' == 'net10.0'" Version="10.*-*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Condition="'$(TargetFramework)' == 'net10.0'" Version="10.*-*" />
    <PackageReference Include="Radzen.Terser.MSBuild" Version="0.0.4" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Include="LICENSE.txt" Pack="true" PackagePath="" />
    <None Include="icon.png" Pack="true" PackagePath="" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="LinkerConfig.xml">
      <LogicalName>$(MSBuildProjectName).xml</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <DartSassOutputStyle>compressed</DartSassOutputStyle>
    <EnableDefaultSassItems>false</EnableDefaultSassItems>
  </PropertyGroup>

  <ItemGroup>
    <Sass Include="$(MSBuildProjectDirectory)/themes/*.scss" Exclude="$(MSBuildProjectDirectory)/themes/_*.scss" Condition="'$(TargetFramework)' == 'net10.0'" />
  </ItemGroup>

 <Target Name="Sass" BeforeTargets="BeforeBuild" Condition="'$(TargetFramework)' == 'net10.0'">
    <PropertyGroup>
      <_SassFileList>@(Sass->'&quot;%(FullPath)&quot;', ' ')</_SassFileList>
      <DartSassBuilderArgs>files $(_SassFileList) --outputstyle $(DartSassOutputStyle) --level $(DartSassOutputLevel)</DartSassBuilderArgs>
    </PropertyGroup>
    <Message Text="$(DartSassBuilderArgs)" Importance="$(DartSassMessageLevel)" />
    <Message Text="Converted SassFile list to argument" Importance="$(DartSassMessageLevel)" />
  </Target>

  <Target Name="MoveCss" AfterTargets="AfterCompile" Condition="'$(TargetFramework)' == 'net10.0'">
    <ItemGroup>
        <CssFile Include="$(MSBuildProjectDirectory)/themes/*.css" />
    </ItemGroup>
    <Move SourceFiles="@(CssFile)" DestinationFolder="$(MSBuildProjectDirectory)/wwwroot/css/" />
  </Target>

  <Target Name="MinifyTest" BeforeTargets="Build" Condition="'$(TargetFramework)' == 'net10.0'">
    <TerserMinify InputFile="wwwroot\Radzen.Blazor.js" OutputFile="wwwroot\Radzen.Blazor.min.js" />
  </Target>

  <ItemGroup Label="Allow internal method to be visible to the unit tests">
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Radzen.Blazor.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
